### ISSUE TITLE
Not supported .xls files

### ISSUE THREAD

**Issue by ukrarome** [django-stars/telega-mega-import#9]
https://github.com/django-stars/telega-mega-import/blob/06063b58f5ff3c45c756f858ad411de4cc43eeab/telega_megaimport/parser.py#L365-L367
I think you forgot to check for file extension:
```python
elif not self.is_csv:
    if extension not in ('.xls', '.xlsx'):
        raise CommandError('Wrong file format. Supported are: .xlsx, .xls')
    self.work_book = open_workbook(self.filename)
```

**Comment by Tengro** [comment]
Fixed in commit.
